removing gateway.watsonplatform.net
IBM/build-react-native-app-for-watson-discovery pull request #27
Opened 2021-05-25 22:09 UTC by ljbennett62

removed/updated service watson-platform-net url.  Can you test verify this pattern - as I tried to install the XCODE and don't seem to have enough space to install.

2021-05-25 22:32 UTC, markstur requested changes
There is a typo in the hhttps

2021-05-25 22:32 UTC, markstur commented on ReactNativeCodePattern/src/discovery.js
> +  const url_dql = `hhttps://api.us-south.discovery.watson.cloud.ibm.com/v1/environments/system/collections/news-en/query?version=2018-08-01&aggregation=filter%28enriched_title.entities.type%3A%3AComp
typo.  There is an extra h in hhttps

2021-05-25 23:05 UTC, markstur reviewed
That's better.  When Rich tests this he should consider making it work in all regions instead of just us-south.  This looks like the correct first fix for removing the obsolete domain, but next I think it is too hard-coded (not a new problem though).

2021-05-28 16:50 UTC, rhagarty approved these changes
url change looks good

2021-05-28 16:50 UTC, merged